name: Build
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [8, 11, 16]
            fail-fast: true
        steps:
            - uses: actions/checkout@v2
            - name: JDK ${{ matrix.java }}
              uses: actions/setup-java@v2
              with:
                  java-version: ${{ matrix.java }}
                  distribution: 'adopt'
            - name: Cache maven
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.m2/repository/
                  key: ${{ runner.os }}-chewtils-${{ hashFiles('**/build.gradle/') }}
                  restore-keys: ${{ runner.os }}-chewtils
            - name: Patch and build
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "Github Actions"
                  ./chewtil build
